Fix issue with airbrake and rails 7
We recently spotted that the app was returning a 404 in our AWS environments even though everything was fine locally. Looking at the logs we found

```
F, [2022-02-21T12:14:47.250216 #1091] FATAL -- : [8b24e26f-674a-4822-8e30-00572c9c75cc]
[8b24e26f-674a-4822-8e30-00572c9c75cc] NoMethodError (undefined method `glob?' for nil:NilClass):
[8b24e26f-674a-4822-8e30-00572c9c75cc]
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/journey/route.rb:138:in `glob?'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rails/app.rb:48:in `block (2 levels) in recognize_route'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/journey/router.rb:74:in `block in recognize'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/journey/router.rb:66:in `each'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/journey/router.rb:66:in `recognize'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rails/app.rb:35:in `block in recognize_route'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rails/app.rb:34:in `each'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rails/app.rb:34:in `recognize_route'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rack/route_filter.rb:30:in `rails_route'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rack/route_filter.rb:21:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake-ruby (5.2.0) lib/airbrake-ruby/filter_chain.rb:74:in `block in refine'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake-ruby (5.2.0) lib/airbrake-ruby/filter_chain.rb:71:in `each'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake-ruby (5.2.0) lib/airbrake-ruby/filter_chain.rb:71:in `refine'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake-ruby (5.2.0) lib/airbrake-ruby/notice_notifier.rb:113:in `send_notice'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake-ruby (5.2.0) lib/airbrake-ruby/notice_notifier.rb:36:in `notify'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake-ruby (5.2.0) lib/airbrake-ruby.rb:181:in `notify'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rack/middleware.rb:75:in `notify_airbrake'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rack/middleware.rb:36:in `rescue in call!'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rack/middleware.rb:33:in `call!'
[8b24e26f-674a-4822-8e30-00572c9c75cc] airbrake (11.0.3) lib/airbrake/rack/middleware.rb:23:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] railties (7.0.1) lib/rails/rack/logger.rb:36:in `call_app'
[8b24e26f-674a-4822-8e30-00572c9c75cc] railties (7.0.1) lib/rails/rack/logger.rb:25:in `block in call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] activesupport (7.0.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[8b24e26f-674a-4822-8e30-00572c9c75cc] activesupport (7.0.1) lib/active_support/tagged_logging.rb:37:in `tagged'
[8b24e26f-674a-4822-8e30-00572c9c75cc] activesupport (7.0.1) lib/active_support/tagged_logging.rb:99:in `tagged'
[8b24e26f-674a-4822-8e30-00572c9c75cc] railties (7.0.1) lib/rails/rack/logger.rb:25:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/middleware/ssl.rb:77:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] actionpack (7.0.1) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] secure_headers (6.3.3) lib/secure_headers/middleware.rb:11:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] railties (7.0.1) lib/rails/engine.rb:530:in `call'
[8b24e26f-674a-4822-8e30-00572c9c75cc] passenger (5.3.7) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
[8b24e26f-674a-4822-8e30-00572c9c75cc] passenger (5.3.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
[8b24e26f-674a-4822-8e30-00572c9c75cc] passenger (5.3.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
[8b24e26f-674a-4822-8e30-00572c9c75cc] passenger (5.3.7) src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
[8b24e26f-674a-4822-8e30-00572c9c75cc] passenger (5.3.7) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

A quick google got us to these stackoverflow posts

- [How to resolve NoMethodError: undefined method `glob?' for nil:NilClass in Rails 7](https://stackoverflow.com/q/70827859/6117745)
- [Rails 7 Update Breaking in Production on Heroku](https://stackoverflow.com/a/70716345/6117745)

A change in action patch caused something to throw an error what Airbrake was previously relying on to fail silently. Fortunately, Airbrake have fixed this in a later version so we just need to update the gem.