Update pg gem
Resolves following error seen when running migrations after the `bundle update`

```
rake aborted!
LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? can't activate pg (~> 1.1), already activated pg-0.21.0. Make sure all dependencies are added to Gemfile.
```